apiVersion: v1
kind: ConfigMap
metadata:
  name: observer-configmap
  namespace: observer
  labels:
    bot: conformitron
data:
  Namespace: observer
  prNumber: "135"
  commitHash: 8b66fc0e9411e68ce3bdc2db4a12b2611e20ff4f
