apiVersion: v1
kind: ConfigMap
metadata:
  name: ee-failing-configmap
  namespace: ee-failing
  labels:
    bot: conformitron
data:
  Namespace: ee-failing
  prNumber: "133"
  commitHash: 6b81d4e4ac4463f24ce9724ce1f999a7388560ba
